version: '2'
services:
    redis_master:
        ##image: redis
        build:
            context: .
            dockerfile: Dockerfile
        container_name: redis_master
        ports:
          - "6379:6379"
        restart: always
        expose: 
            - 6379
        ##command: /bin/bash -c "redis-server /etc/redis/redis.conf"
    redis_worker_01:
        image: redis
        container_name: redis_worker_01
        ports:
          - "6380:6379"
        restart: always
        expose: 
            - 6379
        command: /bin/bash -c "sleep 2 && redis-server --port 6380 --slaveof redis_master 6379"
        depends_on: 
          - redis_master
    redis_worker_02:
        image: redis
        container_name: redis_worker_02
        ports:
          - "6381:6379"
        restart: always
        expose: 
            - 6379
        command: /bin/bash -c "sleep 2 && redis-server --port 6381 --slaveof redis_master 6379"
        depends_on: 
          - redis_master
