version: '3'
services:
  redis_master:
    ##image: redis
    build:
      context: ./redis/
      args:
        REDIS_VERSION: ${REDIS_VERSION}
      dockerfile: Dockerfile
    container_name: redis_master
    env_file:
      - ./.env
    ports:
      - "6379:6379"
    restart: always
    expose: 
      - 6379
    ##command: /bin/bash -c "redis-server /etc/redis/redis.conf"
  redis_worker_01:
    image: redis:${REDIS_VERSION}
    container_name: redis_worker_01
    env_file:
      - ./.env
    ports:
      - "6380:6379"
    restart: always
    expose: 
      - 6379
    command: /bin/bash -c "sleep 2 && redis-server --port 6380 --slaveof redis_master 6379"
    depends_on: 
      - redis_master
  redis_worker_02:
    image: redis:${REDIS_VERSION}
    container_name: redis_worker_02
    env_file:
      - ./.env
    ports:
      - "6381:6379"
    restart: always
    expose: 
      - 6379
    command: /bin/bash -c "sleep 2 && redis-server --port 6381 --slaveof redis_master 6379"
    depends_on: 
      - redis_master
